### PR TITLE
Make minimqtt look like requests

### PR DESCRIPTION
**Pull request by askpatrickw**
PR related to https://github.com/adafruit/Adafruit_CircuitPython_MiniMQTT/issues/43

### CODE REVIEW

**Comment by askpatrickw** [comment]
I'm going to ignore Pylint for now it is related to the new checks.
Happy to try fixing them later though.

**Comment by askpatrickw** [comment]
I'm having another look at this. I see several misses...

**Comment by askpatrickw** [comment]
OK... I cleaned up a few things.
1. I had confused the sub_module and the _socket_pool in the original codes with the changes I wanted to make. Similiar for the SSL context.
2. When I added self as a parameter to _get_socket, that changed the number parameters so when connect was calling _get_socket it was missing 1.

So not that is fixed I have hit 
```python
Traceback (most recent call last):
  File "code.py", line 88, in <module>
  File "adafruit_minimqtt/adafruit_minimqtt.py", line 308, in connect
  File "adafruit_minimqtt/adafruit_minimqtt.py", line 125, in _get_socket
OSError: Failed SSL handshake
```

**Comment by askpatrickw** [comment]
Interesting same code on the WROVER gets further (line numbers might be diff I had some extra Prints in this) but it is getting passed _get_socket and failing in _wait_for_msg

```python
Traceback (most recent call last):
  File "code.py", line 88, in <module>
  File "adafruit_minimqtt/adafruit_minimqtt.py", line 374, in connect
  File "adafruit_minimqtt/adafruit_minimqtt.py", line 718, in _wait_for_msg
AttributeError: 'SocketPool' object has no attribute 'timeout'
```

**Comment by askpatrickw** [comment]
I moved the code in try except and it got by that error about Socket not having a timeout. 
I can now see the core issue, this will need to be modified to work with the new Socket in a much more substantial way.

I kind of follow the logic in the new requests but a that scope of change is beyond me to do in my evenings and would need a lot of hand holding so I'm going to close this PR and let you all handle it. ;-)

**Comment by brentru** [comment]
@askpatrickw  Do you have an ESP32 AirLift board to test against? It might be easier to implement it there first, then move to the ESP32S2. Either way, I'll take a closer look at this when we're ready to modify the library to handle the new socketpool

**Comment by askpatrickw** [comment]
@brentru  I do not have such a board. The integrated WiFi of the S2 sort of ticks all the boxes for my interests.

**Comment by askpatrickw** [comment]
Old PR. Closing.

**Pull request closed without merging**
